### ISSUE TITLE
FRONT END - Login button not activated

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#10]
Even when i type in login and password login is not activated

![screenshot_20190304_120034](https://user-images.githubusercontent.com/22891710/53729484-a9a88480-3e75-11e9-9073-f76419b0bcc7.jpg)

**Comment by cediim8** [comment]
Hi Peter, I have set a standard password requirement of having letters AND numbers. I am guessing that you do not have any numbers in your password, therefore why it is not enabling it. I will put a hint underneath if you want, otherwise I can remove this restriction completely. Let me know. Thanks. Cedric

**Comment by peterillias** [comment]
Yep lets put notification underneath. But strange, password for peter.illias@gmail.com are simple letters keketina is password
