### ISSUE TITLE
FRONT END - duplicate registration

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#14]
I was able to register same email twice... thats shouldnt happen

![image](https://user-images.githubusercontent.com/22891710/53734293-de233d00-3e83-11e9-9f6f-d32c903d365d.png)

**Comment by cediim8** [comment]
Hi Peter, this shouldn't be possible as Firebase checks for users with the same email address: 
![image](https://user-images.githubusercontent.com/31234136/53772566-93143300-3f32-11e9-90bb-0c206609180e.png)

The database shows 2 users with 'peter.illias@gmail.com', however only one appears in the 'Authentication' section. Is it possible that you deleted your User ID at any point from the 'Authentication' section, however didn't delete it from the database? These two are not unfortunately in sync, you need to manually the user from the database too. That is the only explanation I can come up with for this issue, because the user registration API from Firebase simply does not allow this issue to happen in the first place.

![image](https://user-images.githubusercontent.com/31234136/53772710-264d6880-3f33-11e9-98e5-3b938ce885b2.png)

![image](https://user-images.githubusercontent.com/31234136/53772759-5ac12480-3f33-11e9-9c3f-282b4ccf76a7.png)

**Comment by peterillias** [comment]
Ahh you right ! i deleted only user from authentication tab in firebase back end.  Thank you for explanation
