### ISSUE TITLE
FRONT END - Youtube policy

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#18]
:( just found out :( what we going to do ? do you know how much 1 GB cost in FIREBASE if we use firebase to store video instead of YOUTUBE ?

https://www.thepolyglotdeveloper.com/2015/01/embed-video-ios-android-ionicframework-app/

"I have an app for our church, which access youtube videos from our channel , I created the app and submitted the app no problems, but when i made a new update of the app and submitted the update. i got a email from Google that my app update is rejected , reason. it violates our device and network abuse policy.Your app shouldn’t access or use a service or API in a manner that violates its terms of service. For example, make sure your app doesn’t download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service .

This is how i access the youtube. I have a wordpress blog which has the sermons with the youtube video id. i get it to the app and then i pass it to the iframe embed code as you have in the post. DO you have any idea what might be wrong ? I got the app accepted when i submitted the app for the first time, but i have not made any changes to the youtube embed code since then."

**Comment by cediim8** [comment]
Hi Peter, from reading a few more comments on the issue, it seems these people were not correctly handling the playback of Youtube videos and they were still playing in the background, which is something Youtube does not allow. However, the videos in your app are in a separate screen, meaning there is no way that the videos would be playing in the background when you leave the view because it is destroyed. I think the chance of getting rejected by Youtube and Google is quite low.
